### PR TITLE
attempting to fix arbitrary command injection

### PR DESCRIPTION
**Pull request by maltfield**
let me know if you can find any ways to break this attempt to add input sanitation

### CODE REVIEW

**Comment by maltfield** [comment]
actually, the safest thing is probably to just put it in an `env` block, which doesn't appear to be vulnerable to string termination attacks

**Comment by victoriadrake** [comment]
I'm in the process of cleaning up, but I thought I'd leave this hilariousness here for posterity:

Screenshot_20200712_160434

**Comment by maltfield** [comment]
lmao I didn't even notice that one ;)

**Comment by victoriadrake** [comment]
Suggestions incorporated in https://github.com/victoriadrake/github-guestbook/commit/c72d1eb3ad583ed9ee1425eadb0e3b2b52e17235. Thank you!

**Pull request closed without merging**
